
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 12;
  public static final int AND = 14;
  public static final int CLASS = 16;
  public static final int PLUS = 10;
  public static final int LP = 6;
  public static final int RP = 7;
  public static final int NOT = 15;
  public static final int IDENTIFIER = 28;
  public static final int TRUE = 26;
  public static final int PUBLIC = 18;
  public static final int STATIC = 19;
  public static final int LC = 4;
  public static final int LB = 8;
  public static final int RC = 5;
  public static final int LIT_INT = 25;
  public static final int STRING = 21;
  public static final int RB = 9;
  public static final int EOF = 0;
  public static final int PRINTLN = 24;
  public static final int MAIN = 17;
  public static final int SYSTEM = 22;
  public static final int FALSE = 27;
  public static final int SEP = 3;
  public static final int MINUS = 11;
  public static final int error = 1;
  public static final int DOT = 2;
  public static final int OUT = 23;
  public static final int VOID = 20;
  public static final int LESS = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "SEP",
  "LC",
  "RC",
  "LP",
  "RP",
  "LB",
  "RB",
  "PLUS",
  "MINUS",
  "TIMES",
  "LESS",
  "AND",
  "NOT",
  "CLASS",
  "MAIN",
  "PUBLIC",
  "STATIC",
  "VOID",
  "STRING",
  "SYSTEM",
  "OUT",
  "PRINTLN",
  "LIT_INT",
  "TRUE",
  "FALSE",
  "IDENTIFIER"
  };
}

