
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NL = 3;
  public static final int error = 1;
  public static final int PLUS = 4;
  public static final int LP = 5;
  public static final int RP = 6;
  public static final int ENTIER = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTIER",
  "NL",
  "PLUS",
  "LP",
  "RP"
  };
}

